/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddOn {
  'id' : string,
  'name' : string,
  'category' : string,
  'price' : bigint,
}
export interface AddressPublic {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'street' : string,
  'principal' : Principal,
  'displayName' : string,
  'city' : string,
  'zipCode' : string,
  'state' : string,
  'isDefault' : boolean,
}
export type AuthResult = { 'ok' : UserProfile } |
  { 'err' : string };
export type BannerResult = { 'ok' : PromoBannerPublic } |
  { 'err' : string };
export interface CartItem {
  'productId' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Category {
  'id' : string,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface CouponPublic {
  'discountValue' : bigint,
  'expiresAt' : [] | [Time],
  'code' : string,
  'discountType' : DiscountType,
  'usageCount' : bigint,
  'isActive' : boolean,
  'maxUsages' : bigint,
  'triggerProductId' : [] | [string],
  'minOrderAmount' : bigint,
  'requiresMinQty' : bigint,
  'freeProductId' : [] | [string],
}
export interface CouponValidation {
  'discountAmount' : bigint,
  'message' : string,
  'isValid' : boolean,
}
export type Crust = { 'hand_tossed' : null } |
  { 'thin' : null } |
  { 'stuffed' : null };
export interface CrustVariant {
  'displayName' : string,
  'crust' : Crust,
  'extraPrice' : bigint,
}
export type DeleteResult = { 'ok' : null } |
  { 'err' : string };
export interface DeliveryLocation { 'lat' : number, 'lng' : number }
export type DiscountType = { 'bogo' : null } |
  { 'flat' : null } |
  { 'free_delivery' : null } |
  { 'percentage' : null };
export interface LoyaltyAccountPublic {
  'userId' : Principal,
  'joinedAt' : Time,
  'tier' : LoyaltyTier,
  'totalPointsEarned' : bigint,
  'points' : bigint,
}
export type LoyaltyTier = { 'bronze' : null } |
  { 'gold' : null } |
  { 'silver' : null };
export type NotifResult = { 'ok' : null } |
  { 'err' : string };
export interface NotificationPublic {
  'id' : string,
  'title' : string,
  'notifType' : NotificationType,
  'userId' : Principal,
  'createdAt' : Time,
  'read' : boolean,
  'orderId' : [] | [string],
  'message' : string,
}
export type NotificationType = { 'orderConfirmed' : null } |
  { 'couponExpiry' : null } |
  { 'outForDelivery' : null } |
  { 'orderPreparing' : null } |
  { 'orderCancelled' : null } |
  { 'promoAlert' : null } |
  { 'orderDelivered' : null };
export interface OrderItem {
  'size' : string,
  'crust' : string,
  'productId' : string,
  'productName' : string,
  'imageUrl' : string,
  'addOns' : Array<string>,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'totalPrice' : bigint,
}
export interface OrderOut {
  'id' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'couponCode' : [] | [string],
  'total' : bigint,
  'deliveryPartnerLocation' : [] | [DeliveryLocation],
  'paymentRefunded' : boolean,
  'deliveryFee' : bigint,
  'cancellationReason' : [] | [string],
  'discountAmount' : bigint,
  'estimatedDeliveryMinutes' : bigint,
  'updatedAt' : bigint,
  'placedAt' : bigint,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
  'paymentVerified' : boolean,
  'deliveryPartnerId' : [] | [Principal],
  'paymentIntentId' : [] | [string],
  'subtotal' : bigint,
}
export interface OrderReview {
  'id' : string,
  'createdAt' : Time,
  'orderId' : string,
  'comment' : [] | [string],
  'overallRating' : bigint,
  'productRatings' : Array<ProductRating>,
  'customerId' : Principal,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'placed' : null } |
  { 'out_for_delivery' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface PointsTransaction {
  'id' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'description' : string,
  'txnType' : { 'redeemed' : null } |
    { 'earned' : null },
  'orderId' : [] | [string],
  'points' : bigint,
}
export interface Product {
  'id' : string,
  'categoryId' : string,
  'ratingCount' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'isArchived' : boolean,
  'sizes' : Array<SizeVariant>,
  'imageUrl' : string,
  'crusts' : Array<CrustVariant>,
  'addOns' : Array<string>,
  'rating' : number,
  'basePrice' : bigint,
}
export interface ProductRating { 'productId' : string, 'rating' : bigint }
export interface ProductUpdate {
  'categoryId' : [] | [string],
  'name' : [] | [string],
  'isAvailable' : [] | [boolean],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
  'basePrice' : [] | [bigint],
}
export interface PromoBannerPublic {
  'id' : string,
  'couponCode' : [] | [string],
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'ctaLink' : string,
  'imageUrl' : string,
  'ctaText' : string,
  'priority' : bigint,
}
export type ReviewResult = { 'ok' : OrderReview } |
  { 'err' : string };
export type Role = { 'admin' : null } |
  { 'customer' : null } |
  { 'delivery_partner' : null };
export type Size = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface SizeVariant {
  'displayName' : string,
  'size' : Size,
  'priceMultiplier' : number,
}
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'role' : Role,
  'phone' : string,
}
export type UsersResult = { 'ok' : Array<UserProfile> } |
  { 'err' : string };
export interface _SERVICE {
  'acceptOrder' : ActorMethod<[string], boolean>,
  'applyCoupon' : ActorMethod<[string, bigint], CouponValidation>,
  'assignDeliveryPartner' : ActorMethod<[string, Principal], boolean>,
  'autoApplyCoupon' : ActorMethod<
    [bigint, Array<CartItem>],
    [] | [CouponPublic]
  >,
  'cancelOrder' : ActorMethod<[string, string], string>,
  'createAddOn' : ActorMethod<[AddOn], undefined>,
  'createBanner' : ActorMethod<
    [string, string, string, string, string, [] | [string], bigint],
    BannerResult
  >,
  'createCategory' : ActorMethod<[Category], undefined>,
  'createCoupon' : ActorMethod<
    [
      string,
      DiscountType,
      bigint,
      bigint,
      bigint,
      [] | [Time],
      [] | [string],
      [] | [string],
      bigint,
    ],
    CouponPublic
  >,
  'createProduct' : ActorMethod<[Product], undefined>,
  'createProfile' : ActorMethod<[Role, string, string], AuthResult>,
  'deleteAddOn' : ActorMethod<[string], boolean>,
  'deleteAddress' : ActorMethod<[string], boolean>,
  'deleteBanner' : ActorMethod<[string], DeleteResult>,
  'deleteCategory' : ActorMethod<[string], string>,
  'deleteProduct' : ActorMethod<[string], boolean>,
  'getActiveBanners' : ActorMethod<[], Array<PromoBannerPublic>>,
  'getAddOns' : ActorMethod<[], Array<AddOn>>,
  'getAddresses' : ActorMethod<[], Array<AddressPublic>>,
  'getAllReviews' : ActorMethod<[], Array<OrderReview>>,
  'getAllUsers' : ActorMethod<[], UsersResult>,
  'getAvailableOrders' : ActorMethod<[], Array<OrderOut>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCoupons' : ActorMethod<[], Array<CouponPublic>>,
  'getDeliveryFee' : ActorMethod<
    [string],
    [] | [
      {
        'feeInCents' : bigint,
        'distanceKm' : number,
        'estimatedMinutes' : bigint,
      }
    ]
  >,
  'getLoyaltyAccount' : ActorMethod<[], [] | [LoyaltyAccountPublic]>,
  'getMyAssignedOrders' : ActorMethod<[], Array<OrderOut>>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationPublic>>,
  'getMyOrders' : ActorMethod<[], Array<OrderOut>>,
  'getOrder' : ActorMethod<[string], [] | [OrderOut]>,
  'getOrderForReorder' : ActorMethod<
    [string],
    { 'ok' : Array<OrderItem> } |
      { 'err' : string }
  >,
  'getOrderReview' : ActorMethod<[string], [] | [OrderReview]>,
  'getOrderStats' : ActorMethod<
    [],
    [] | [
      {
        'cancelledCount' : bigint,
        'totalOrders' : bigint,
        'outForDelivery' : bigint,
        'activeDeliveries' : bigint,
        'confirmedCount' : bigint,
        'todayRevenue' : bigint,
        'preparingCount' : bigint,
        'deliveredCount' : bigint,
        'totalRevenue' : bigint,
        'placedCount' : bigint,
        'avgOrderValue' : bigint,
        'todayOrders' : bigint,
      }
    ]
  >,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<OrderOut>>,
  'getPartnerStats' : ActorMethod<
    [],
    {
      'todayDeliveries' : bigint,
      'totalDelivered' : bigint,
      'activeOrders' : bigint,
    }
  >,
  'getPointsHistory' : ActorMethod<[], Array<PointsTransaction>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getRole' : ActorMethod<[], Role>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[string], NotifResult>,
  'placeOrder' : ActorMethod<
    [
      Array<OrderItem>,
      bigint,
      bigint,
      bigint,
      bigint,
      [] | [string],
      string,
      bigint,
    ],
    OrderOut
  >,
  'rejectOrder' : ActorMethod<[string], boolean>,
  'saveAddress' : ActorMethod<
    [string, string, string, string, string, number, number],
    AddressPublic
  >,
  'setAdminRole' : ActorMethod<[Principal, boolean], AuthResult>,
  'setDefaultAddress' : ActorMethod<[string], boolean>,
  'submitOrderReview' : ActorMethod<
    [string, bigint, [] | [string]],
    ReviewResult
  >,
  'toggleBannerActive' : ActorMethod<[string], BannerResult>,
  'updateAddOn' : ActorMethod<[string, string, bigint], boolean>,
  'updateBanner' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
    ],
    BannerResult
  >,
  'updateCategory' : ActorMethod<
    [string, string, [] | [string], [] | [bigint]],
    boolean
  >,
  'updateDeliveryLocation' : ActorMethod<[string, number, number], boolean>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<[string, ProductUpdate], boolean>,
  'updateProfile' : ActorMethod<[string, string], AuthResult>,
  'validateCoupon' : ActorMethod<[string, bigint], CouponValidation>,
  'verifyAndConfirmOrder' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];