/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CouponValidation = IDL.Record({
  'discountAmount' : IDL.Nat,
  'message' : IDL.Text,
  'isValid' : IDL.Bool,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Time = IDL.Int;
export const DiscountType = IDL.Variant({
  'bogo' : IDL.Null,
  'flat' : IDL.Null,
  'free_delivery' : IDL.Null,
  'percentage' : IDL.Null,
});
export const CouponPublic = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiresAt' : IDL.Opt(Time),
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'usageCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUsages' : IDL.Nat,
  'triggerProductId' : IDL.Opt(IDL.Text),
  'minOrderAmount' : IDL.Nat,
  'requiresMinQty' : IDL.Nat,
  'freeProductId' : IDL.Opt(IDL.Text),
});
export const AddOn = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const PromoBannerPublic = IDL.Record({
  'id' : IDL.Text,
  'couponCode' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'ctaLink' : IDL.Text,
  'imageUrl' : IDL.Text,
  'ctaText' : IDL.Text,
  'priority' : IDL.Nat,
});
export const BannerResult = IDL.Variant({
  'ok' : PromoBannerPublic,
  'err' : IDL.Text,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Size = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const SizeVariant = IDL.Record({
  'displayName' : IDL.Text,
  'size' : Size,
  'priceMultiplier' : IDL.Float64,
});
export const Crust = IDL.Variant({
  'hand_tossed' : IDL.Null,
  'thin' : IDL.Null,
  'stuffed' : IDL.Null,
});
export const CrustVariant = IDL.Record({
  'displayName' : IDL.Text,
  'crust' : Crust,
  'extraPrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'ratingCount' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'isArchived' : IDL.Bool,
  'sizes' : IDL.Vec(SizeVariant),
  'imageUrl' : IDL.Text,
  'crusts' : IDL.Vec(CrustVariant),
  'addOns' : IDL.Vec(IDL.Text),
  'rating' : IDL.Float64,
  'basePrice' : IDL.Nat,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'delivery_partner' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : Role,
  'phone' : IDL.Text,
});
export const AuthResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const DeleteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const AddressPublic = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'street' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'city' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'isDefault' : IDL.Bool,
});
export const ProductRating = IDL.Record({
  'productId' : IDL.Text,
  'rating' : IDL.Nat,
});
export const OrderReview = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'comment' : IDL.Opt(IDL.Text),
  'overallRating' : IDL.Nat,
  'productRatings' : IDL.Vec(ProductRating),
  'customerId' : IDL.Principal,
});
export const UsersResult = IDL.Variant({
  'ok' : IDL.Vec(UserProfile),
  'err' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'placed' : IDL.Null,
  'out_for_delivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const DeliveryLocation = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const OrderItem = IDL.Record({
  'size' : IDL.Text,
  'crust' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'imageUrl' : IDL.Text,
  'addOns' : IDL.Vec(IDL.Text),
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});
export const OrderOut = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'couponCode' : IDL.Opt(IDL.Text),
  'total' : IDL.Nat,
  'deliveryPartnerLocation' : IDL.Opt(DeliveryLocation),
  'paymentRefunded' : IDL.Bool,
  'deliveryFee' : IDL.Nat,
  'cancellationReason' : IDL.Opt(IDL.Text),
  'discountAmount' : IDL.Nat,
  'estimatedDeliveryMinutes' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'placedAt' : IDL.Int,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'paymentVerified' : IDL.Bool,
  'deliveryPartnerId' : IDL.Opt(IDL.Principal),
  'paymentIntentId' : IDL.Opt(IDL.Text),
  'subtotal' : IDL.Nat,
});
export const LoyaltyTier = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'silver' : IDL.Null,
});
export const LoyaltyAccountPublic = IDL.Record({
  'userId' : IDL.Principal,
  'joinedAt' : Time,
  'tier' : LoyaltyTier,
  'totalPointsEarned' : IDL.Nat,
  'points' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'orderConfirmed' : IDL.Null,
  'couponExpiry' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'orderPreparing' : IDL.Null,
  'orderCancelled' : IDL.Null,
  'promoAlert' : IDL.Null,
  'orderDelivered' : IDL.Null,
});
export const NotificationPublic = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'read' : IDL.Bool,
  'orderId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
});
export const PointsTransaction = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'txnType' : IDL.Variant({ 'redeemed' : IDL.Null, 'earned' : IDL.Null }),
  'orderId' : IDL.Opt(IDL.Text),
  'points' : IDL.Int,
});
export const NotifResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const ReviewResult = IDL.Variant({
  'ok' : OrderReview,
  'err' : IDL.Text,
});
export const ProductUpdate = IDL.Record({
  'categoryId' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'isAvailable' : IDL.Opt(IDL.Bool),
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'basePrice' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'acceptOrder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'applyCoupon' : IDL.Func([IDL.Text, IDL.Nat], [CouponValidation], []),
  'assignDeliveryPartner' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], []),
  'autoApplyCoupon' : IDL.Func(
      [IDL.Nat, IDL.Vec(CartItem)],
      [IDL.Opt(CouponPublic)],
      [],
    ),
  'cancelOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createAddOn' : IDL.Func([AddOn], [], []),
  'createBanner' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [BannerResult],
      [],
    ),
  'createCategory' : IDL.Func([Category], [], []),
  'createCoupon' : IDL.Func(
      [
        IDL.Text,
        DiscountType,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(Time),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [CouponPublic],
      [],
    ),
  'createProduct' : IDL.Func([Product], [], []),
  'createProfile' : IDL.Func([Role, IDL.Text, IDL.Text], [AuthResult], []),
  'deleteAddOn' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBanner' : IDL.Func([IDL.Text], [DeleteResult], []),
  'deleteCategory' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getActiveBanners' : IDL.Func([], [IDL.Vec(PromoBannerPublic)], ['query']),
  'getAddOns' : IDL.Func([], [IDL.Vec(AddOn)], ['query']),
  'getAddresses' : IDL.Func([], [IDL.Vec(AddressPublic)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(OrderReview)], []),
  'getAllUsers' : IDL.Func([], [UsersResult], ['query']),
  'getAvailableOrders' : IDL.Func([], [IDL.Vec(OrderOut)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
  'getDeliveryFee' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'feeInCents' : IDL.Nat,
            'distanceKm' : IDL.Float64,
            'estimatedMinutes' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getLoyaltyAccount' : IDL.Func([], [IDL.Opt(LoyaltyAccountPublic)], []),
  'getMyAssignedOrders' : IDL.Func([], [IDL.Vec(OrderOut)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], []),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderOut)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderOut)], ['query']),
  'getOrderForReorder' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderItem), 'err' : IDL.Text })],
      ['query'],
    ),
  'getOrderReview' : IDL.Func([IDL.Text], [IDL.Opt(OrderReview)], ['query']),
  'getOrderStats' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'cancelledCount' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'outForDelivery' : IDL.Nat,
            'activeDeliveries' : IDL.Nat,
            'confirmedCount' : IDL.Nat,
            'todayRevenue' : IDL.Nat,
            'preparingCount' : IDL.Nat,
            'deliveredCount' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'placedCount' : IDL.Nat,
            'avgOrderValue' : IDL.Nat,
            'todayOrders' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(OrderOut)], ['query']),
  'getPartnerStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'todayDeliveries' : IDL.Nat,
          'totalDelivered' : IDL.Nat,
          'activeOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPointsHistory' : IDL.Func([], [IDL.Vec(PointsTransaction)], []),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getRole' : IDL.Func([], [Role], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], []),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [NotifResult], []),
  'placeOrder' : IDL.Func(
      [
        IDL.Vec(OrderItem),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Nat,
      ],
      [OrderOut],
      [],
    ),
  'rejectOrder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveAddress' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [AddressPublic],
      [],
    ),
  'setAdminRole' : IDL.Func([IDL.Principal, IDL.Bool], [AuthResult], []),
  'setDefaultAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitOrderReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [ReviewResult],
      [],
    ),
  'toggleBannerActive' : IDL.Func([IDL.Text], [BannerResult], []),
  'updateAddOn' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Bool], []),
  'updateBanner' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [BannerResult],
      [],
    ),
  'updateCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Bool],
      [],
    ),
  'updateDeliveryLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [IDL.Bool], []),
  'updateProduct' : IDL.Func([IDL.Text, ProductUpdate], [IDL.Bool], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'validateCoupon' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [CouponValidation],
      ['query'],
    ),
  'verifyAndConfirmOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CouponValidation = IDL.Record({
    'discountAmount' : IDL.Nat,
    'message' : IDL.Text,
    'isValid' : IDL.Bool,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Time = IDL.Int;
  const DiscountType = IDL.Variant({
    'bogo' : IDL.Null,
    'flat' : IDL.Null,
    'free_delivery' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const CouponPublic = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiresAt' : IDL.Opt(Time),
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'usageCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUsages' : IDL.Nat,
    'triggerProductId' : IDL.Opt(IDL.Text),
    'minOrderAmount' : IDL.Nat,
    'requiresMinQty' : IDL.Nat,
    'freeProductId' : IDL.Opt(IDL.Text),
  });
  const AddOn = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PromoBannerPublic = IDL.Record({
    'id' : IDL.Text,
    'couponCode' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'ctaLink' : IDL.Text,
    'imageUrl' : IDL.Text,
    'ctaText' : IDL.Text,
    'priority' : IDL.Nat,
  });
  const BannerResult = IDL.Variant({
    'ok' : PromoBannerPublic,
    'err' : IDL.Text,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Size = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const SizeVariant = IDL.Record({
    'displayName' : IDL.Text,
    'size' : Size,
    'priceMultiplier' : IDL.Float64,
  });
  const Crust = IDL.Variant({
    'hand_tossed' : IDL.Null,
    'thin' : IDL.Null,
    'stuffed' : IDL.Null,
  });
  const CrustVariant = IDL.Record({
    'displayName' : IDL.Text,
    'crust' : Crust,
    'extraPrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'ratingCount' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'isArchived' : IDL.Bool,
    'sizes' : IDL.Vec(SizeVariant),
    'imageUrl' : IDL.Text,
    'crusts' : IDL.Vec(CrustVariant),
    'addOns' : IDL.Vec(IDL.Text),
    'rating' : IDL.Float64,
    'basePrice' : IDL.Nat,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'delivery_partner' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : Role,
    'phone' : IDL.Text,
  });
  const AuthResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const DeleteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AddressPublic = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'street' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'city' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  const ProductRating = IDL.Record({
    'productId' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const OrderReview = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'comment' : IDL.Opt(IDL.Text),
    'overallRating' : IDL.Nat,
    'productRatings' : IDL.Vec(ProductRating),
    'customerId' : IDL.Principal,
  });
  const UsersResult = IDL.Variant({
    'ok' : IDL.Vec(UserProfile),
    'err' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'placed' : IDL.Null,
    'out_for_delivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const DeliveryLocation = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
  });
  const OrderItem = IDL.Record({
    'size' : IDL.Text,
    'crust' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'imageUrl' : IDL.Text,
    'addOns' : IDL.Vec(IDL.Text),
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  const OrderOut = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'couponCode' : IDL.Opt(IDL.Text),
    'total' : IDL.Nat,
    'deliveryPartnerLocation' : IDL.Opt(DeliveryLocation),
    'paymentRefunded' : IDL.Bool,
    'deliveryFee' : IDL.Nat,
    'cancellationReason' : IDL.Opt(IDL.Text),
    'discountAmount' : IDL.Nat,
    'estimatedDeliveryMinutes' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'placedAt' : IDL.Int,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'paymentVerified' : IDL.Bool,
    'deliveryPartnerId' : IDL.Opt(IDL.Principal),
    'paymentIntentId' : IDL.Opt(IDL.Text),
    'subtotal' : IDL.Nat,
  });
  const LoyaltyTier = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'silver' : IDL.Null,
  });
  const LoyaltyAccountPublic = IDL.Record({
    'userId' : IDL.Principal,
    'joinedAt' : Time,
    'tier' : LoyaltyTier,
    'totalPointsEarned' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'orderConfirmed' : IDL.Null,
    'couponExpiry' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'orderPreparing' : IDL.Null,
    'orderCancelled' : IDL.Null,
    'promoAlert' : IDL.Null,
    'orderDelivered' : IDL.Null,
  });
  const NotificationPublic = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'read' : IDL.Bool,
    'orderId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
  });
  const PointsTransaction = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'txnType' : IDL.Variant({ 'redeemed' : IDL.Null, 'earned' : IDL.Null }),
    'orderId' : IDL.Opt(IDL.Text),
    'points' : IDL.Int,
  });
  const NotifResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const ReviewResult = IDL.Variant({ 'ok' : OrderReview, 'err' : IDL.Text });
  const ProductUpdate = IDL.Record({
    'categoryId' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'isAvailable' : IDL.Opt(IDL.Bool),
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'basePrice' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'acceptOrder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'applyCoupon' : IDL.Func([IDL.Text, IDL.Nat], [CouponValidation], []),
    'assignDeliveryPartner' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Bool],
        [],
      ),
    'autoApplyCoupon' : IDL.Func(
        [IDL.Nat, IDL.Vec(CartItem)],
        [IDL.Opt(CouponPublic)],
        [],
      ),
    'cancelOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createAddOn' : IDL.Func([AddOn], [], []),
    'createBanner' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [BannerResult],
        [],
      ),
    'createCategory' : IDL.Func([Category], [], []),
    'createCoupon' : IDL.Func(
        [
          IDL.Text,
          DiscountType,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(Time),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [CouponPublic],
        [],
      ),
    'createProduct' : IDL.Func([Product], [], []),
    'createProfile' : IDL.Func([Role, IDL.Text, IDL.Text], [AuthResult], []),
    'deleteAddOn' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBanner' : IDL.Func([IDL.Text], [DeleteResult], []),
    'deleteCategory' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getActiveBanners' : IDL.Func([], [IDL.Vec(PromoBannerPublic)], ['query']),
    'getAddOns' : IDL.Func([], [IDL.Vec(AddOn)], ['query']),
    'getAddresses' : IDL.Func([], [IDL.Vec(AddressPublic)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(OrderReview)], []),
    'getAllUsers' : IDL.Func([], [UsersResult], ['query']),
    'getAvailableOrders' : IDL.Func([], [IDL.Vec(OrderOut)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
    'getDeliveryFee' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'feeInCents' : IDL.Nat,
              'distanceKm' : IDL.Float64,
              'estimatedMinutes' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getLoyaltyAccount' : IDL.Func([], [IDL.Opt(LoyaltyAccountPublic)], []),
    'getMyAssignedOrders' : IDL.Func([], [IDL.Vec(OrderOut)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], []),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderOut)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderOut)], ['query']),
    'getOrderForReorder' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderItem), 'err' : IDL.Text })],
        ['query'],
      ),
    'getOrderReview' : IDL.Func([IDL.Text], [IDL.Opt(OrderReview)], ['query']),
    'getOrderStats' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'cancelledCount' : IDL.Nat,
              'totalOrders' : IDL.Nat,
              'outForDelivery' : IDL.Nat,
              'activeDeliveries' : IDL.Nat,
              'confirmedCount' : IDL.Nat,
              'todayRevenue' : IDL.Nat,
              'preparingCount' : IDL.Nat,
              'deliveredCount' : IDL.Nat,
              'totalRevenue' : IDL.Nat,
              'placedCount' : IDL.Nat,
              'avgOrderValue' : IDL.Nat,
              'todayOrders' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(OrderOut)],
        ['query'],
      ),
    'getPartnerStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'todayDeliveries' : IDL.Nat,
            'totalDelivered' : IDL.Nat,
            'activeOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPointsHistory' : IDL.Func([], [IDL.Vec(PointsTransaction)], []),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getRole' : IDL.Func([], [Role], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], []),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [NotifResult], []),
    'placeOrder' : IDL.Func(
        [
          IDL.Vec(OrderItem),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Nat,
        ],
        [OrderOut],
        [],
      ),
    'rejectOrder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveAddress' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [AddressPublic],
        [],
      ),
    'setAdminRole' : IDL.Func([IDL.Principal, IDL.Bool], [AuthResult], []),
    'setDefaultAddress' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitOrderReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [ReviewResult],
        [],
      ),
    'toggleBannerActive' : IDL.Func([IDL.Text], [BannerResult], []),
    'updateAddOn' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Bool], []),
    'updateBanner' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [BannerResult],
        [],
      ),
    'updateCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Bool],
        [],
      ),
    'updateDeliveryLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [IDL.Bool], []),
    'updateProduct' : IDL.Func([IDL.Text, ProductUpdate], [IDL.Bool], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'validateCoupon' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [CouponValidation],
        ['query'],
      ),
    'verifyAndConfirmOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };