/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: string;
    categoryId: string;
    ratingCount: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    isArchived: boolean;
    sizes: Array<SizeVariant>;
    imageUrl: string;
    crusts: Array<CrustVariant>;
    addOns: Array<string>;
    rating: number;
    basePrice: bigint;
}
export interface UserProfile {
    principal: Principal;
    name: string;
    createdAt: Time;
    role: Role;
    phone: string;
}
export type UsersResult = {
    __kind__: "ok";
    ok: Array<UserProfile>;
} | {
    __kind__: "err";
    err: string;
};
export type Time = bigint;
export interface AddOn {
    id: string;
    name: string;
    category: string;
    price: bigint;
}
export interface OrderItem {
    size: string;
    crust: string;
    productId: string;
    productName: string;
    imageUrl: string;
    addOns: Array<string>;
    quantity: bigint;
    unitPrice: bigint;
    totalPrice: bigint;
}
export type DeleteResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type ReviewResult = {
    __kind__: "ok";
    ok: OrderReview;
} | {
    __kind__: "err";
    err: string;
};
export interface PromoBannerPublic {
    id: string;
    couponCode?: string;
    title: string;
    createdAt: Time;
    description: string;
    isActive: boolean;
    ctaLink: string;
    imageUrl: string;
    ctaText: string;
    priority: bigint;
}
export interface CouponPublic {
    discountValue: bigint;
    expiresAt?: Time;
    code: string;
    discountType: DiscountType;
    usageCount: bigint;
    isActive: boolean;
    maxUsages: bigint;
    triggerProductId?: string;
    minOrderAmount: bigint;
    requiresMinQty: bigint;
    freeProductId?: string;
}
export interface SizeVariant {
    displayName: string;
    size: Size;
    priceMultiplier: number;
}
export interface CouponValidation {
    discountAmount: bigint;
    message: string;
    isValid: boolean;
}
export interface AddressPublic {
    id: string;
    lat: number;
    lng: number;
    street: string;
    principal: Principal;
    displayName: string;
    city: string;
    zipCode: string;
    state: string;
    isDefault: boolean;
}
export type AuthResult = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface NotificationPublic {
    id: string;
    title: string;
    notifType: NotificationType;
    userId: Principal;
    createdAt: Time;
    read: boolean;
    orderId?: string;
    message: string;
}
export type NotifResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Category {
    id: string;
    sortOrder: bigint;
    name: string;
    description: string;
    imageUrl: string;
}
export type BannerResult = {
    __kind__: "ok";
    ok: PromoBannerPublic;
} | {
    __kind__: "err";
    err: string;
};
export interface ProductUpdate {
    categoryId?: string;
    name?: string;
    isAvailable?: boolean;
    description?: string;
    imageUrl?: string;
    basePrice?: bigint;
}
export interface LoyaltyAccountPublic {
    userId: Principal;
    joinedAt: Time;
    tier: LoyaltyTier;
    totalPointsEarned: bigint;
    points: bigint;
}
export interface OrderReview {
    id: string;
    createdAt: Time;
    orderId: string;
    comment?: string;
    overallRating: bigint;
    productRatings: Array<ProductRating>;
    customerId: Principal;
}
export interface PointsTransaction {
    id: string;
    userId: Principal;
    createdAt: Time;
    description: string;
    txnType: Variant_redeemed_earned;
    orderId?: string;
    points: bigint;
}
export interface ProductRating {
    productId: string;
    rating: bigint;
}
export interface DeliveryLocation {
    lat: number;
    lng: number;
}
export interface CrustVariant {
    displayName: string;
    crust: Crust;
    extraPrice: bigint;
}
export interface CartItem {
    productId: string;
    quantity: bigint;
    unitPrice: bigint;
}
export interface OrderOut {
    id: string;
    status: OrderStatus;
    deliveryAddress: string;
    couponCode?: string;
    total: bigint;
    deliveryPartnerLocation?: DeliveryLocation;
    paymentRefunded: boolean;
    deliveryFee: bigint;
    cancellationReason?: string;
    discountAmount: bigint;
    estimatedDeliveryMinutes: bigint;
    updatedAt: bigint;
    placedAt: bigint;
    customerId: Principal;
    items: Array<OrderItem>;
    paymentVerified: boolean;
    deliveryPartnerId?: Principal;
    paymentIntentId?: string;
    subtotal: bigint;
}
export enum Crust {
    hand_tossed = "hand_tossed",
    thin = "thin",
    stuffed = "stuffed"
}
export enum DiscountType {
    bogo = "bogo",
    flat = "flat",
    free_delivery = "free_delivery",
    percentage = "percentage"
}
export enum LoyaltyTier {
    bronze = "bronze",
    gold = "gold",
    silver = "silver"
}
export enum NotificationType {
    orderConfirmed = "orderConfirmed",
    couponExpiry = "couponExpiry",
    outForDelivery = "outForDelivery",
    orderPreparing = "orderPreparing",
    orderCancelled = "orderCancelled",
    promoAlert = "promoAlert",
    orderDelivered = "orderDelivered"
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    placed = "placed",
    out_for_delivery = "out_for_delivery",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum Role {
    admin = "admin",
    customer = "customer",
    delivery_partner = "delivery_partner"
}
export enum Size {
    large = "large",
    small = "small",
    medium = "medium"
}
export enum Variant_redeemed_earned {
    redeemed = "redeemed",
    earned = "earned"
}
export interface backendInterface {
    acceptOrder(orderId: string): Promise<boolean>;
    applyCoupon(code: string, orderTotal: bigint): Promise<CouponValidation>;
    assignDeliveryPartner(orderId: string, partnerId: Principal): Promise<boolean>;
    autoApplyCoupon(cartTotal: bigint, cartItems: Array<CartItem>): Promise<CouponPublic | null>;
    cancelOrder(orderId: string, reason: string): Promise<string>;
    createAddOn(addOn: AddOn): Promise<void>;
    createBanner(title: string, description: string, imageUrl: string, ctaText: string, ctaLink: string, couponCode: string | null, priority: bigint): Promise<BannerResult>;
    createCategory(category: Category): Promise<void>;
    createCoupon(code: string, discountType: DiscountType, discountValue: bigint, minOrderAmount: bigint, maxUsages: bigint, expiresAt: Time | null, triggerProductId: string | null, freeProductId: string | null, requiresMinQty: bigint): Promise<CouponPublic>;
    createProduct(product: Product): Promise<void>;
    createProfile(role: Role, name: string, phone: string): Promise<AuthResult>;
    deleteAddOn(addOnId: string): Promise<boolean>;
    deleteAddress(id: string): Promise<boolean>;
    deleteBanner(id: string): Promise<DeleteResult>;
    deleteCategory(categoryId: string): Promise<string>;
    deleteProduct(productId: string): Promise<boolean>;
    getActiveBanners(): Promise<Array<PromoBannerPublic>>;
    getAddOns(): Promise<Array<AddOn>>;
    getAddresses(): Promise<Array<AddressPublic>>;
    getAllReviews(): Promise<Array<OrderReview>>;
    getAllUsers(): Promise<UsersResult>;
    getAvailableOrders(): Promise<Array<OrderOut>>;
    getCategories(): Promise<Array<Category>>;
    getCoupons(): Promise<Array<CouponPublic>>;
    getDeliveryFee(addressId: string): Promise<{
        feeInCents: bigint;
        distanceKm: number;
        estimatedMinutes: bigint;
    } | null>;
    getLoyaltyAccount(): Promise<LoyaltyAccountPublic | null>;
    getMyAssignedOrders(): Promise<Array<OrderOut>>;
    getMyNotifications(): Promise<Array<NotificationPublic>>;
    getMyOrders(): Promise<Array<OrderOut>>;
    getOrder(id: string): Promise<OrderOut | null>;
    getOrderForReorder(orderId: string): Promise<{
        __kind__: "ok";
        ok: Array<OrderItem>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getOrderReview(orderId: string): Promise<OrderReview | null>;
    getOrderStats(): Promise<{
        cancelledCount: bigint;
        totalOrders: bigint;
        outForDelivery: bigint;
        activeDeliveries: bigint;
        confirmedCount: bigint;
        todayRevenue: bigint;
        preparingCount: bigint;
        deliveredCount: bigint;
        totalRevenue: bigint;
        placedCount: bigint;
        avgOrderValue: bigint;
        todayOrders: bigint;
    } | null>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<OrderOut>>;
    getPartnerStats(): Promise<{
        todayDeliveries: bigint;
        totalDelivered: bigint;
        activeOrders: bigint;
    }>;
    getPointsHistory(): Promise<Array<PointsTransaction>>;
    getProduct(id: string): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getProductsByCategory(categoryId: string): Promise<Array<Product>>;
    getProfile(): Promise<UserProfile | null>;
    getRole(): Promise<Role>;
    getUnreadCount(): Promise<bigint>;
    isAuthenticated(): Promise<boolean>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(id: string): Promise<NotifResult>;
    placeOrder(items: Array<OrderItem>, subtotal: bigint, deliveryFee: bigint, discountAmount: bigint, total: bigint, couponCode: string | null, deliveryAddress: string, estimatedDeliveryMinutes: bigint): Promise<OrderOut>;
    rejectOrder(orderId: string): Promise<boolean>;
    saveAddress(displayName: string, street: string, city: string, state: string, zipCode: string, lat: number, lng: number): Promise<AddressPublic>;
    setAdminRole(targetPrincipal: Principal, makeAdmin: boolean): Promise<AuthResult>;
    setDefaultAddress(id: string): Promise<boolean>;
    submitOrderReview(orderId: string, rating: bigint, comment: string | null): Promise<ReviewResult>;
    toggleBannerActive(id: string): Promise<BannerResult>;
    updateAddOn(addOnId: string, name: string, price: bigint): Promise<boolean>;
    updateBanner(id: string, title: string | null, description: string | null, imageUrl: string | null, ctaText: string | null, ctaLink: string | null, couponCode: string | null, priority: bigint | null): Promise<BannerResult>;
    updateCategory(categoryId: string, name: string, imageUrl: string | null, sortOrder: bigint | null): Promise<boolean>;
    updateDeliveryLocation(orderId: string, lat: number, lng: number): Promise<boolean>;
    updateOrderStatus(id: string, status: OrderStatus): Promise<boolean>;
    updateProduct(productId: string, updates: ProductUpdate): Promise<boolean>;
    updateProfile(name: string, phone: string): Promise<AuthResult>;
    validateCoupon(code: string, orderTotal: bigint): Promise<CouponValidation>;
    verifyAndConfirmOrder(orderId: string, paymentIntentId: string): Promise<boolean>;
}
import type { AuthResult as _AuthResult, BannerResult as _BannerResult, CouponPublic as _CouponPublic, Crust as _Crust, CrustVariant as _CrustVariant, DeleteResult as _DeleteResult, DeliveryLocation as _DeliveryLocation, DiscountType as _DiscountType, LoyaltyAccountPublic as _LoyaltyAccountPublic, LoyaltyTier as _LoyaltyTier, NotifResult as _NotifResult, NotificationPublic as _NotificationPublic, NotificationType as _NotificationType, OrderItem as _OrderItem, OrderOut as _OrderOut, OrderReview as _OrderReview, OrderStatus as _OrderStatus, PointsTransaction as _PointsTransaction, Product as _Product, ProductRating as _ProductRating, ProductUpdate as _ProductUpdate, PromoBannerPublic as _PromoBannerPublic, ReviewResult as _ReviewResult, Role as _Role, Size as _Size, SizeVariant as _SizeVariant, Time as _Time, UserProfile as _UserProfile, UsersResult as _UsersResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptOrder(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptOrder(arg0);
            return result;
        }
    }
    async applyCoupon(arg0: string, arg1: bigint): Promise<CouponValidation> {
        if (this.processError) {
            try {
                const result = await this.actor.applyCoupon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyCoupon(arg0, arg1);
            return result;
        }
    }
    async assignDeliveryPartner(arg0: string, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDeliveryPartner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDeliveryPartner(arg0, arg1);
            return result;
        }
    }
    async autoApplyCoupon(arg0: bigint, arg1: Array<CartItem>): Promise<CouponPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.autoApplyCoupon(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoApplyCoupon(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelOrder(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0, arg1);
            return result;
        }
    }
    async createAddOn(arg0: AddOn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAddOn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAddOn(arg0);
            return result;
        }
    }
    async createBanner(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: bigint): Promise<BannerResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createBanner(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6);
                return from_candid_BannerResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBanner(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6);
            return from_candid_BannerResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createCoupon(arg0: string, arg1: DiscountType, arg2: bigint, arg3: bigint, arg4: bigint, arg5: Time | null, arg6: string | null, arg7: string | null, arg8: bigint): Promise<CouponPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0, to_candid_DiscountType_n13(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), arg8);
                return from_candid_CouponPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0, to_candid_DiscountType_n13(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), arg8);
            return from_candid_CouponPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_Product_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_Product_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProfile(arg0: Role, arg1: string, arg2: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(to_candid_Role_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_AuthResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(to_candid_Role_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_AuthResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAddOn(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddOn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddOn(arg0);
            return result;
        }
    }
    async deleteAddress(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddress(arg0);
            return result;
        }
    }
    async deleteBanner(arg0: string): Promise<DeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBanner(arg0);
                return from_candid_DeleteResult_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBanner(arg0);
            return from_candid_DeleteResult_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCategory(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getActiveBanners(): Promise<Array<PromoBannerPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveBanners();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveBanners();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAddOns(): Promise<Array<AddOn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAddOns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAddOns();
            return result;
        }
    }
    async getAddresses(): Promise<Array<AddressPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAddresses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAddresses();
            return result;
        }
    }
    async getAllReviews(): Promise<Array<OrderReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<UsersResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_UsersResult_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_UsersResult_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableOrders(): Promise<Array<OrderOut>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableOrders();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableOrders();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCoupons(): Promise<Array<CouponPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupons();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupons();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryFee(arg0: string): Promise<{
        feeInCents: bigint;
        distanceKm: number;
        estimatedMinutes: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryFee(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryFee(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoyaltyAccount(): Promise<LoyaltyAccountPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoyaltyAccount();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoyaltyAccount();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAssignedOrders(): Promise<Array<OrderOut>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAssignedOrders();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAssignedOrders();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<NotificationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<OrderOut>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<OrderOut | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderForReorder(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<OrderItem>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderForReorder(arg0);
                return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderForReorder(arg0);
            return from_candid_variant_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderReview(arg0: string): Promise<OrderReview | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderReview(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderReview(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderStats(): Promise<{
        cancelledCount: bigint;
        totalOrders: bigint;
        outForDelivery: bigint;
        activeDeliveries: bigint;
        confirmedCount: bigint;
        todayRevenue: bigint;
        preparingCount: bigint;
        deliveredCount: bigint;
        totalRevenue: bigint;
        placedCount: bigint;
        avgOrderValue: bigint;
        todayOrders: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStats();
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStats();
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<OrderOut>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n68(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n68(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerStats(): Promise<{
        todayDeliveries: bigint;
        totalDelivered: bigint;
        activeOrders: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerStats();
            return result;
        }
    }
    async getPointsHistory(): Promise<Array<PointsTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPointsHistory();
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPointsHistory();
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRole(): Promise<Role> {
        if (this.processError) {
            try {
                const result = await this.actor.getRole();
                return from_candid_Role_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRole();
            return from_candid_Role_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async isAuthenticated(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthenticated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthenticated();
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<NotifResult> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_NotifResult_n89(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_NotifResult_n89(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: Array<OrderItem>, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string | null, arg6: string, arg7: bigint): Promise<OrderOut> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_OrderOut_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_OrderOut_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectOrder(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectOrder(arg0);
            return result;
        }
    }
    async saveAddress(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: number): Promise<AddressPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAddress(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAddress(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async setAdminRole(arg0: Principal, arg1: boolean): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminRole(arg0, arg1);
                return from_candid_AuthResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminRole(arg0, arg1);
            return from_candid_AuthResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDefaultAddress(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultAddress(arg0);
            return result;
        }
    }
    async submitOrderReview(arg0: string, arg1: bigint, arg2: string | null): Promise<ReviewResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrderReview(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ReviewResult_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrderReview(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ReviewResult_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleBannerActive(arg0: string): Promise<BannerResult> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBannerActive(arg0);
                return from_candid_BannerResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBannerActive(arg0);
            return from_candid_BannerResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAddOn(arg0: string, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAddOn(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAddOn(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBanner(arg0: string, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null, arg7: bigint | null): Promise<BannerResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBanner(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg7));
                return from_candid_BannerResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBanner(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg7));
            return from_candid_BannerResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCategory(arg0: string, arg1: string, arg2: string | null, arg3: bigint | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateDeliveryLocation(arg0: string, arg1: number, arg2: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryLocation(arg0, arg1, arg2);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: ProductUpdate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductUpdate_n93(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductUpdate_n93(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return from_candid_AuthResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return from_candid_AuthResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateCoupon(arg0: string, arg1: bigint): Promise<CouponValidation> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0, arg1);
            return result;
        }
    }
    async verifyAndConfirmOrder(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAndConfirmOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAndConfirmOrder(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AuthResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_BannerResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BannerResult): BannerResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CouponPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CouponPublic): CouponPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_CrustVariant_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CrustVariant): CrustVariant {
    return from_candid_record_n84(_uploadFile, _downloadFile, value);
}
function from_candid_Crust_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Crust): Crust {
    return from_candid_variant_n86(_uploadFile, _downloadFile, value);
}
function from_candid_DeleteResult_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteResult): DeleteResult {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_LoyaltyAccountPublic_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoyaltyAccountPublic): LoyaltyAccountPublic {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_LoyaltyTier_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoyaltyTier): LoyaltyTier {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_NotifResult_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotifResult): NotifResult {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPublic_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPublic): NotificationPublic {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_OrderOut_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderOut): OrderOut {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_OrderReview_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderReview): OrderReview {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_PointsTransaction_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointsTransaction): PointsTransaction {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n76(_uploadFile, _downloadFile, value);
}
function from_candid_PromoBannerPublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromoBannerPublic): PromoBannerPublic {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewResult_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewResult): ReviewResult {
    return from_candid_variant_n91(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SizeVariant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SizeVariant): SizeVariant {
    return from_candid_record_n79(_uploadFile, _downloadFile, value);
}
function from_candid_Size_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Size): Size {
    return from_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UsersResult_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UsersResult): UsersResult {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CouponPublic]): CouponPublic | null {
    return value.length === 0 ? null : from_candid_CouponPublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeliveryLocation]): DeliveryLocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        feeInCents: bigint;
        distanceKm: number;
        estimatedMinutes: bigint;
    }]): {
    feeInCents: bigint;
    distanceKm: number;
    estimatedMinutes: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LoyaltyAccountPublic]): LoyaltyAccountPublic | null {
    return value.length === 0 ? null : from_candid_LoyaltyAccountPublic_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderOut]): OrderOut | null {
    return value.length === 0 ? null : from_candid_OrderOut_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderReview]): OrderReview | null {
    return value.length === 0 ? null : from_candid_OrderReview_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        cancelledCount: bigint;
        totalOrders: bigint;
        outForDelivery: bigint;
        activeDeliveries: bigint;
        confirmedCount: bigint;
        todayRevenue: bigint;
        preparingCount: bigint;
        deliveredCount: bigint;
        totalRevenue: bigint;
        placedCount: bigint;
        avgOrderValue: bigint;
        todayOrders: bigint;
    }]): {
    cancelledCount: bigint;
    totalOrders: bigint;
    outForDelivery: bigint;
    activeDeliveries: bigint;
    confirmedCount: bigint;
    todayRevenue: bigint;
    preparingCount: bigint;
    deliveredCount: bigint;
    totalRevenue: bigint;
    placedCount: bigint;
    avgOrderValue: bigint;
    todayOrders: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n75(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    couponCode: [] | [string];
    title: string;
    createdAt: _Time;
    description: string;
    isActive: boolean;
    ctaLink: string;
    imageUrl: string;
    ctaText: string;
    priority: bigint;
}): {
    id: string;
    couponCode?: string;
    title: string;
    createdAt: Time;
    description: string;
    isActive: boolean;
    ctaLink: string;
    imageUrl: string;
    ctaText: string;
    priority: bigint;
} {
    return {
        id: value.id,
        couponCode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.couponCode)),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        ctaLink: value.ctaLink,
        imageUrl: value.imageUrl,
        ctaText: value.ctaText,
        priority: value.priority
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountValue: bigint;
    expiresAt: [] | [_Time];
    code: string;
    discountType: _DiscountType;
    usageCount: bigint;
    isActive: boolean;
    maxUsages: bigint;
    triggerProductId: [] | [string];
    minOrderAmount: bigint;
    requiresMinQty: bigint;
    freeProductId: [] | [string];
}): {
    discountValue: bigint;
    expiresAt?: Time;
    code: string;
    discountType: DiscountType;
    usageCount: bigint;
    isActive: boolean;
    maxUsages: bigint;
    triggerProductId?: string;
    minOrderAmount: bigint;
    requiresMinQty: bigint;
    freeProductId?: string;
} {
    return {
        discountValue: value.discountValue,
        expiresAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.expiresAt)),
        code: value.code,
        discountType: from_candid_DiscountType_n5(_uploadFile, _downloadFile, value.discountType),
        usageCount: value.usageCount,
        isActive: value.isActive,
        maxUsages: value.maxUsages,
        triggerProductId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.triggerProductId)),
        minOrderAmount: value.minOrderAmount,
        requiresMinQty: value.requiresMinQty,
        freeProductId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.freeProductId))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    createdAt: _Time;
    role: _Role;
    phone: string;
}): {
    principal: Principal;
    name: string;
    createdAt: Time;
    role: Role;
    phone: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n34(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: _Time;
    orderId: string;
    comment: [] | [string];
    overallRating: bigint;
    productRatings: Array<_ProductRating>;
    customerId: Principal;
}): {
    id: string;
    createdAt: Time;
    orderId: string;
    comment?: string;
    overallRating: bigint;
    productRatings: Array<ProductRating>;
    customerId: Principal;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        orderId: value.orderId,
        comment: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.comment)),
        overallRating: value.overallRating,
        productRatings: value.productRatings,
        customerId: value.customerId
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    deliveryAddress: string;
    couponCode: [] | [string];
    total: bigint;
    deliveryPartnerLocation: [] | [_DeliveryLocation];
    paymentRefunded: boolean;
    deliveryFee: bigint;
    cancellationReason: [] | [string];
    discountAmount: bigint;
    estimatedDeliveryMinutes: bigint;
    updatedAt: bigint;
    placedAt: bigint;
    customerId: Principal;
    items: Array<_OrderItem>;
    paymentVerified: boolean;
    deliveryPartnerId: [] | [Principal];
    paymentIntentId: [] | [string];
    subtotal: bigint;
}): {
    id: string;
    status: OrderStatus;
    deliveryAddress: string;
    couponCode?: string;
    total: bigint;
    deliveryPartnerLocation?: DeliveryLocation;
    paymentRefunded: boolean;
    deliveryFee: bigint;
    cancellationReason?: string;
    discountAmount: bigint;
    estimatedDeliveryMinutes: bigint;
    updatedAt: bigint;
    placedAt: bigint;
    customerId: Principal;
    items: Array<OrderItem>;
    paymentVerified: boolean;
    deliveryPartnerId?: Principal;
    paymentIntentId?: string;
    subtotal: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n48(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        couponCode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.couponCode)),
        total: value.total,
        deliveryPartnerLocation: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.deliveryPartnerLocation)),
        paymentRefunded: value.paymentRefunded,
        deliveryFee: value.deliveryFee,
        cancellationReason: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cancellationReason)),
        discountAmount: value.discountAmount,
        estimatedDeliveryMinutes: value.estimatedDeliveryMinutes,
        updatedAt: value.updatedAt,
        placedAt: value.placedAt,
        customerId: value.customerId,
        items: value.items,
        paymentVerified: value.paymentVerified,
        deliveryPartnerId: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.deliveryPartnerId)),
        paymentIntentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.paymentIntentId)),
        subtotal: value.subtotal
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: Principal;
    joinedAt: _Time;
    tier: _LoyaltyTier;
    totalPointsEarned: bigint;
    points: bigint;
}): {
    userId: Principal;
    joinedAt: Time;
    tier: LoyaltyTier;
    totalPointsEarned: bigint;
    points: bigint;
} {
    return {
        userId: value.userId,
        joinedAt: value.joinedAt,
        tier: from_candid_LoyaltyTier_n57(_uploadFile, _downloadFile, value.tier),
        totalPointsEarned: value.totalPointsEarned,
        points: value.points
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    notifType: _NotificationType;
    userId: Principal;
    createdAt: _Time;
    read: boolean;
    orderId: [] | [string];
    message: string;
}): {
    id: string;
    title: string;
    notifType: NotificationType;
    userId: Principal;
    createdAt: Time;
    read: boolean;
    orderId?: string;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        notifType: from_candid_NotificationType_n62(_uploadFile, _downloadFile, value.notifType),
        userId: value.userId,
        createdAt: value.createdAt,
        read: value.read,
        orderId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.orderId)),
        message: value.message
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    userId: Principal;
    createdAt: _Time;
    description: string;
    txnType: {
        redeemed: null;
    } | {
        earned: null;
    };
    orderId: [] | [string];
    points: bigint;
}): {
    id: string;
    userId: Principal;
    createdAt: Time;
    description: string;
    txnType: Variant_redeemed_earned;
    orderId?: string;
    points: bigint;
} {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        description: value.description,
        txnType: from_candid_variant_n73(_uploadFile, _downloadFile, value.txnType),
        orderId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.orderId)),
        points: value.points
    };
}
function from_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    ratingCount: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    isArchived: boolean;
    sizes: Array<_SizeVariant>;
    imageUrl: string;
    crusts: Array<_CrustVariant>;
    addOns: Array<string>;
    rating: number;
    basePrice: bigint;
}): {
    id: string;
    categoryId: string;
    ratingCount: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    isArchived: boolean;
    sizes: Array<SizeVariant>;
    imageUrl: string;
    crusts: Array<CrustVariant>;
    addOns: Array<string>;
    rating: number;
    basePrice: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        ratingCount: value.ratingCount,
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        isArchived: value.isArchived,
        sizes: from_candid_vec_n77(_uploadFile, _downloadFile, value.sizes),
        imageUrl: value.imageUrl,
        crusts: from_candid_vec_n82(_uploadFile, _downloadFile, value.crusts),
        addOns: value.addOns,
        rating: value.rating,
        basePrice: value.basePrice
    };
}
function from_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    size: _Size;
    priceMultiplier: number;
}): {
    displayName: string;
    size: Size;
    priceMultiplier: number;
} {
    return {
        displayName: value.displayName,
        size: from_candid_Size_n80(_uploadFile, _downloadFile, value.size),
        priceMultiplier: value.priceMultiplier
    };
}
function from_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    crust: _Crust;
    extraPrice: bigint;
}): {
    displayName: string;
    crust: Crust;
    extraPrice: bigint;
} {
    return {
        displayName: value.displayName,
        crust: from_candid_Crust_n85(_uploadFile, _downloadFile, value.crust),
        extraPrice: value.extraPrice
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PromoBannerPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PromoBannerPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PromoBannerPublic_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    delivery_partner: null;
}): Role {
    return "admin" in value ? Role.admin : "customer" in value ? Role.customer : "delivery_partner" in value ? Role.delivery_partner : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserProfile>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserProfile>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n44(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    placed: null;
} | {
    out_for_delivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "placed" in value ? OrderStatus.placed : "out_for_delivery" in value ? OrderStatus.out_for_delivery : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    gold: null;
} | {
    silver: null;
}): LoyaltyTier {
    return "bronze" in value ? LoyaltyTier.bronze : "gold" in value ? LoyaltyTier.gold : "silver" in value ? LoyaltyTier.silver : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bogo: null;
} | {
    flat: null;
} | {
    free_delivery: null;
} | {
    percentage: null;
}): DiscountType {
    return "bogo" in value ? DiscountType.bogo : "flat" in value ? DiscountType.flat : "free_delivery" in value ? DiscountType.free_delivery : "percentage" in value ? DiscountType.percentage : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orderConfirmed: null;
} | {
    couponExpiry: null;
} | {
    outForDelivery: null;
} | {
    orderPreparing: null;
} | {
    orderCancelled: null;
} | {
    promoAlert: null;
} | {
    orderDelivered: null;
}): NotificationType {
    return "orderConfirmed" in value ? NotificationType.orderConfirmed : "couponExpiry" in value ? NotificationType.couponExpiry : "outForDelivery" in value ? NotificationType.outForDelivery : "orderPreparing" in value ? NotificationType.orderPreparing : "orderCancelled" in value ? NotificationType.orderCancelled : "promoAlert" in value ? NotificationType.promoAlert : "orderDelivered" in value ? NotificationType.orderDelivered : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_OrderItem>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<OrderItem>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    redeemed: null;
} | {
    earned: null;
}): Variant_redeemed_earned {
    return "redeemed" in value ? Variant_redeemed_earned.redeemed : "earned" in value ? Variant_redeemed_earned.earned : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
} | {
    medium: null;
}): Size {
    return "large" in value ? Size.large : "small" in value ? Size.small : "medium" in value ? Size.medium : value;
}
function from_candid_variant_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hand_tossed: null;
} | {
    thin: null;
} | {
    stuffed: null;
}): Crust {
    return "hand_tossed" in value ? Crust.hand_tossed : "thin" in value ? Crust.thin : "stuffed" in value ? Crust.stuffed : value;
}
function from_candid_variant_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _OrderReview;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: OrderReview;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_OrderReview_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PromoBannerPublic>): Array<PromoBannerPublic> {
    return value.map((x)=>from_candid_PromoBannerPublic_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderReview>): Array<OrderReview> {
    return value.map((x)=>from_candid_OrderReview_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderOut>): Array<OrderOut> {
    return value.map((x)=>from_candid_OrderOut_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CouponPublic>): Array<CouponPublic> {
    return value.map((x)=>from_candid_CouponPublic_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationPublic>): Array<NotificationPublic> {
    return value.map((x)=>from_candid_NotificationPublic_n60(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PointsTransaction>): Array<PointsTransaction> {
    return value.map((x)=>from_candid_PointsTransaction_n71(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SizeVariant>): Array<SizeVariant> {
    return value.map((x)=>from_candid_SizeVariant_n78(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CrustVariant>): Array<CrustVariant> {
    return value.map((x)=>from_candid_CrustVariant_n83(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n75(_uploadFile, _downloadFile, x));
}
function to_candid_CrustVariant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CrustVariant): _CrustVariant {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Crust_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Crust): _Crust {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_DiscountType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_ProductUpdate_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUpdate): _ProductUpdate {
    return to_candid_record_n94(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_SizeVariant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SizeVariant): _SizeVariant {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Size_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Size): _Size {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    ratingCount: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    isArchived: boolean;
    sizes: Array<SizeVariant>;
    imageUrl: string;
    crusts: Array<CrustVariant>;
    addOns: Array<string>;
    rating: number;
    basePrice: bigint;
}): {
    id: string;
    categoryId: string;
    ratingCount: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    isArchived: boolean;
    sizes: Array<_SizeVariant>;
    imageUrl: string;
    crusts: Array<_CrustVariant>;
    addOns: Array<string>;
    rating: number;
    basePrice: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        ratingCount: value.ratingCount,
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        isArchived: value.isArchived,
        sizes: to_candid_vec_n18(_uploadFile, _downloadFile, value.sizes),
        imageUrl: value.imageUrl,
        crusts: to_candid_vec_n23(_uploadFile, _downloadFile, value.crusts),
        addOns: value.addOns,
        rating: value.rating,
        basePrice: value.basePrice
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    size: Size;
    priceMultiplier: number;
}): {
    displayName: string;
    size: _Size;
    priceMultiplier: number;
} {
    return {
        displayName: value.displayName,
        size: to_candid_Size_n21(_uploadFile, _downloadFile, value.size),
        priceMultiplier: value.priceMultiplier
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    crust: Crust;
    extraPrice: bigint;
}): {
    displayName: string;
    crust: _Crust;
    extraPrice: bigint;
} {
    return {
        displayName: value.displayName,
        crust: to_candid_Crust_n26(_uploadFile, _downloadFile, value.crust),
        extraPrice: value.extraPrice
    };
}
function to_candid_record_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId?: string;
    name?: string;
    isAvailable?: boolean;
    description?: string;
    imageUrl?: string;
    basePrice?: bigint;
}): {
    categoryId: [] | [string];
    name: [] | [string];
    isAvailable: [] | [boolean];
    description: [] | [string];
    imageUrl: [] | [string];
    basePrice: [] | [bigint];
} {
    return {
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        isAvailable: value.isAvailable ? candid_some(value.isAvailable) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        basePrice: value.basePrice ? candid_some(value.basePrice) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    bogo: null;
} | {
    flat: null;
} | {
    free_delivery: null;
} | {
    percentage: null;
} {
    return value == DiscountType.bogo ? {
        bogo: null
    } : value == DiscountType.flat ? {
        flat: null
    } : value == DiscountType.free_delivery ? {
        free_delivery: null
    } : value == DiscountType.percentage ? {
        percentage: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Size): {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == Size.large ? {
        large: null
    } : value == Size.small ? {
        small: null
    } : value == Size.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Crust): {
    hand_tossed: null;
} | {
    thin: null;
} | {
    stuffed: null;
} {
    return value == Crust.hand_tossed ? {
        hand_tossed: null
    } : value == Crust.thin ? {
        thin: null
    } : value == Crust.stuffed ? {
        stuffed: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    customer: null;
} | {
    delivery_partner: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.customer ? {
        customer: null
    } : value == Role.delivery_partner ? {
        delivery_partner: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    placed: null;
} | {
    out_for_delivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.placed ? {
        placed: null
    } : value == OrderStatus.out_for_delivery ? {
        out_for_delivery: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SizeVariant>): Array<_SizeVariant> {
    return value.map((x)=>to_candid_SizeVariant_n19(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CrustVariant>): Array<_CrustVariant> {
    return value.map((x)=>to_candid_CrustVariant_n24(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
